version: '3.8'

services:
  redis:
    image: redis:7-alpine
    hostname: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    restart: always
    ports:
      - "1267:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - app
    env_file:
      - .env

volumes:
  redis_data:

